# Generated by Django 4.1.2 on 2022-10-26 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='titulo',
            new_name='title',
        ),
    ]
