# Generated by Django 4.1.2 on 2022-10-26 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0002_rename_titulo_projects_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='github',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
