# Generated by Django 4.1.2 on 2022-10-27 14:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0004_rename_projects_project_projectdetail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectdetail',
            old_name='thumb1',
            new_name='gif',
        ),
        migrations.RenameField(
            model_name='projectdetail',
            old_name='thumb2',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='project',
            name='thumb',
        ),
        migrations.AddField(
            model_name='project',
            name='template',
            field=models.ImageField(default='null', upload_to='project_templates'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Stack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('icon', models.ImageField(upload_to='icon_stack')),
                ('description', models.TextField(max_length=1000)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('projects', models.ManyToManyField(to='homePage.project')),
            ],
        ),
    ]
