# Generated by Django 4.1.2 on 2022-10-28 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0005_rename_thumb1_projectdetail_gif_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stack',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='stack',
            name='description',
        ),
        migrations.AddField(
            model_name='stack',
            name='category',
            field=models.CharField(choices=[('BACKEND', 'Back-end'), ('FRONTEND', 'Front-end'), ('DATABASE', 'Database'), ('FRAMEWORK', 'Framework'), ('LIBS', 'libraries'), ('TOOL', 'Tool')], default='null', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stack',
            name='projects',
            field=models.ManyToManyField(related_name='stack', to='homePage.project'),
        ),
    ]
