# Generated by Django 4.1.2 on 2022-10-29 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0006_rename_title_stack_name_remove_stack_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stack',
            name='category',
            field=models.CharField(choices=[('BACKEND', 'Back-end'), ('FRONTEND', 'Front-end'), ('DATABASE', 'Database'), ('FRAMEWORK', 'Framework'), ('CLOUD', 'Cloud'), ('LIBS', 'libraries'), ('TOOL', 'Tool')], max_length=100),
        ),
    ]
