# Generated by Django 4.1.2 on 2022-10-30 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0009_alter_project_user'),
        ('authUser', '0002_userdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='projects',
            field=models.ManyToManyField(related_name='projects', to='homePage.project'),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='stacks',
            field=models.ManyToManyField(related_name='stacks', to='homePage.stack'),
        ),
    ]
