# Generated by Django 4.1.2 on 2022-10-30 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authUser', '0004_formation_experience_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='start',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='experience',
            name='end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='experience',
            name='start',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='formation',
            name='end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='formation',
            name='start',
            field=models.DateField(),
        ),
    ]
